apiVersion: v1
kind: Pod
metadata: 
    name: my-app-pod
    labels: 
        app: my-app    
        env: production
        tier: backend
spec:
    containers:
      - name: my-app-container
        image: nginx:latest
